USE [AZURE_FICRMMSCRM]

IF EXISTS (
        SELECT 1
          FROM SYS.views AS V
          JOIN SYS.schemas AS S
            ON V.schema_id = S.schema_id
         WHERE V.name = 'vfi_fi_financialplanningserviceauditlogBase'
           AND S.name = 'edwreader'
)
DROP VIEW edwreader.vfi_fi_financialplanningserviceauditlogBase
GO

CREATE VIEW [edwreader].[vfi_fi_financialplanningserviceauditlogBase]
AS
SELECT [fi_fi_financialplanningserviceauditlogId]
     , [CreatedOn]
     , [CreatedBy]
     , [ModifiedOn]
     , [ModifiedBy]
     , [CreatedOnBehalfBy]
     , [ModifiedOnBehalfBy]
     , [OrganizationId]
     , [statecode]
     , [statuscode]
     , [VersionNumber]
     , [ImportSequenceNumber]
     , [OverriddenCreatedOn]
     , [TimeZoneRuleVersionNumber]
     , [UTCConversionTimeZoneCode]
     , [fi_name]
     , [fi_ActivityTopic1]
     , [fi_ActivityTopic2]
     , [fi_ActivityTopic3]
     , [fi_ActivityTopic4]
     , [fi_ActivityTopic5]
     , [fi_FinancialPlanningServiceId]
     , [fi_Id]
     , [fi_id_search]
     , [fi_StatusCode]
     , [fi_StateCode]
     , [fi_assignedon]
     , [fi_assignedtouserid]
     , [fi_clientengagementlettersenton]
     , [fi_clientinforeceivedon]
     , [fi_completedon]
     , [fi_contactid]
     , [fi_deliverablecompletedon]
     , [fi_deliverablestartedon]
     , [fi_educationsavings]
     , [fi_engagementletterreceivedon]
     , [fi_giftingcharitable]
     , [fi_healthinsurancemedicare]
     , [fi_icinvolvement]
     , [fi_initialcallscheduledon]
     , [fi_insurancelifeliabilityumbrella]
     , [fi_internalpointofcontact]
     , [fi_longtermcare]
     , [fi_nextappointmenton]
     , [fi_pensionnuastockoptions]
     , [fi_prioryeartaxreturnreceivedon]
     , [fi_qcperformedon]
     , [fi_realestatereversemortgages]
     , [fi_requestdetail]
     , [fi_retirementplanningbudgeting]
     , [fi_reviewedwithclienton]
     , [fi_rrwithic]
     , [fi_senttoclienton]
     , [fi_submittedon]
     , [fi_taxplanningaccountsequencing]
     , [fi_termthreat]
     , [fi_timesensitive]
     , [fi_workbooksenton]
     , [fi_workingwith]
     , [fi_xmltransport]
     , [fi_servicerequested]
     , [fi_subtype]
     , [fi_WorknoteId]
  FROM [FICRM_MSCRM].[dbo].[fi_fi_financialplanningserviceauditlogBase] (NOLOCK)
